"use strict";
let car = 'Subaru';
console.log("Is car == 'Subaru'? I predict True.");
console.log(car == 'Subaru');
let age = 18;
console.log("Is age > 19? I predict false");
console.log(age > 19);
let color = "Blue";
console.log("Is color = Red || color = Blue? I predict true ");
console.log(color == "Red" || color == "Blue");
let relationship = "Brother";
console.log("Is relationship != Brother? I predict false");
console.log(relationship != "Brother");
let laptop_brand = "Lenovo";
console.log("Is laptop_brand = Lenovo && laptop_brand != Dell? I predict True");
console.log(laptop_brand != "Dell" && laptop_brand == "Lenovo");
let points = 16;
console.log("Is points >=16 || points<15 ? I predict True");
console.log(points >= 16 || points < 15);
